/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package rocks.matrixgames.android.mtxRendererService;


public enum Direction implements org.apache.thrift.TEnum {
  UP(0),
  RIGHT(1),
  DOWN(2),
  LEFT(3);

  private final int value;

  private Direction(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Direction findByValue(int value) { 
    switch (value) {
      case 0:
        return UP;
      case 1:
        return RIGHT;
      case 2:
        return DOWN;
      case 3:
        return LEFT;
      default:
        return null;
    }
  }
}
