/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package rocks.matrixgames.android.mtxRendererService;


public enum GroundTexture implements org.apache.thrift.TEnum {
  NONE(0),
  RANDOM(1),
  GRAS(2),
  WOOD(3),
  ROCK(4),
  SAND(5),
  LAVA(6),
  SNOW(7),
  ICE(8),
  EARTH(9),
  METAL(10),
  MARBLE(11),
  PAVEMENT(12),
  CONCRETE(13);

  private final int value;

  private GroundTexture(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GroundTexture findByValue(int value) { 
    switch (value) {
      case 0:
        return NONE;
      case 1:
        return RANDOM;
      case 2:
        return GRAS;
      case 3:
        return WOOD;
      case 4:
        return ROCK;
      case 5:
        return SAND;
      case 6:
        return LAVA;
      case 7:
        return SNOW;
      case 8:
        return ICE;
      case 9:
        return EARTH;
      case 10:
        return METAL;
      case 11:
        return MARBLE;
      case 12:
        return PAVEMENT;
      case 13:
        return CONCRETE;
      default:
        return null;
    }
  }
}
