/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package rocks.matrixgames.android.mtxRendererService;


public enum WallTexture implements org.apache.thrift.TEnum {
  RED_BRICKS(0),
  WHITE_BRICKS(1);

  private final int value;

  private WallTexture(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static WallTexture findByValue(int value) { 
    switch (value) {
      case 0:
        return RED_BRICKS;
      case 1:
        return WHITE_BRICKS;
      default:
        return null;
    }
  }
}
